[platformio]
default_envs = anchor-66

[env]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified @ ^0.2.8
build_flags =
    -DCORE_DEBUG_LEVEL=3

[env:anchor-66]
build_flags =
    ${env.build_flags}
    -DUWB_ANCHOR_ID=0

[env:anchor-77]
build_flags =
    ${env.build_flags}
    -DUWB_ANCHOR_ID=1
