[platformio]
default_envs = atoms3r-m12

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified @ ^0.2.8
    m5stack/M5_BMM150
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Iinclude

[env:atoms3r-m12]
board = m5stack-atoms3
board_build.arduino.memory_type = qio_opi
build_flags =
    ${env.build_flags}

[env:m5stickc-plus]
board = m5stick-c
build_flags =
    ${env.build_flags}
    -DTAG_M5STICKC_PLUS
    -DM5GFX_BOARD=board_M5StickCPlus
